version: '2'

services:
   php:
    image: 539238261458.dkr.ecr.us-east-1.amazonaws.com/php-laravel-xdebug:latest
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    restart: always
    volumes:
       - .:/var/www/html
    mem_limit: 1g
networks:
  default:
    external:
      name: dev
